# kind-config.yaml

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: multi-node-cluster

# Defining control-plane node and worker nodes
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
