apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/k8s_testing
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PORT: "3306"
