apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/fluentd.pos
      format json
      time_key time
      time_format %Y-%m-%dT%H:%M:%S
      tag kubernetes.*
    </source>

    <match kubernetes.**>
      @type loki
      @id out_loki
      url "http://loki.monitoring.svc.cluster.local:3100/api/prom/push"
      <buffer>
        flush_interval 5s
      </buffer>
    </match>
